# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'films_wid.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(770, 363)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(20, 20, 111, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(20, 70, 111, 41))
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(140, 20, 621, 321))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.comboBox.setItemText(0, _translate("Form", "комедия"))
        self.comboBox.setItemText(1, _translate("Form", "драма"))
        self.comboBox.setItemText(2, _translate("Form", "мелодрама"))
        self.comboBox.setItemText(3, _translate("Form", "детектив"))
        self.comboBox.setItemText(4, _translate("Form", "документальный"))
        self.comboBox.setItemText(5, _translate("Form", "ужасы"))
        self.comboBox.setItemText(6, _translate("Form", "музыка"))
        self.comboBox.setItemText(7, _translate("Form", "фантастика"))
        self.comboBox.setItemText(8, _translate("Form", "анимация"))
        self.comboBox.setItemText(9, _translate("Form", "биография"))
        self.comboBox.setItemText(10, _translate("Form", "боевик"))
        self.comboBox.setItemText(11, _translate("Form", "приключения"))
        self.comboBox.setItemText(12, _translate("Form", "война"))
        self.comboBox.setItemText(13, _translate("Form", "семейный"))
        self.comboBox.setItemText(14, _translate("Form", "триллер"))
        self.comboBox.setItemText(15, _translate("Form", "фэнтези"))
        self.comboBox.setItemText(16, _translate("Form", "вестерн"))
        self.comboBox.setItemText(17, _translate("Form", "мистика"))
        self.comboBox.setItemText(18, _translate("Form", "короткометражный"))
        self.comboBox.setItemText(19, _translate("Form", "мюзикл"))
        self.comboBox.setItemText(20, _translate("Form", "исторический"))
        self.comboBox.setItemText(21, _translate("Form", "нуар"))
        self.pushButton.setText(_translate("Form", "Пуск"))
